apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-deployment
  namespace: test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
        - name: simple-flask-app
          image: git.fritz.box/root/mini_flask:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-loadbalancer
  namespace: test2
spec:
  ports:
    - port: 81
      targetPort: 8000
      protocol: TCP
  selector:
    app: simple-flask-app
  externalIPs:
    - 192.168.178.42
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.178.42
      - ip: 192.168.178.43
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-flask-app-ingress
  namespace: test2
spec:
  ingressClassName: traefik
  rules:
    - host: flask2.k3s-master
    - http:
        paths:
          - path: /
            backend:
              service: 
                name: simple-flask-loadbalancer
                port:
                  number: 81
            path: /
            pathType: Prefix
